services:
  app:
    container_name: notes-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - CONFIG_PATH="/app/config/docker.yaml"
    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    container_name: notes-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "notes"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 10