env: local
migrations_path: ./app/migrations
is_reload: false
jwt_secret: "docker-secret"
postgres:
  host: db
  port: 5432
  user: postgres
  password: postgres
  name: postgres
  database: notes
  ssl_mode: disable
http_server:
  address: 0.0.0.0:8181
  timeout: 5s
  idle_timeout: 10s