env: local
migrations_path: ./migrations
is_reload: false
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: postgres
  database: notes
  ssl_mode: disable
http_server:
  address: localhost:8085
  timeout: 5s
  idle_timeout: 10s
authorization:
  secret: "local-secret"
  access_ttl: 168h
  refresh_ttl: 168h
  salt: "local-salt"
image:
  images_dir: "./uploads"
  image_salt: "local-image-salt"
  max_width: 768