env: local
migrations_path: ./migrations
is_reload: true
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: postgres
  database: notes
  ssl_mode: disable
http_server:
  address: localhost:8085
  timeout: 5s
  idle_timeout: 10s